import { AiFillStar } from "react-icons/ai";
import Recommended from "../Recommended/Recommended";

const data = [
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.zASwqDy3PoIGsPKB00VUDwHaHc&pid=Api&P=0&h=180",
    title: "brass bowl",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "TableWare",
    size: "Large",
    category: "Brass Utensils",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.uwV5fh-A5vY6HQkr8tj1SQHaHa&pid=Api&P=0&h=180",
    title: " Water Jug",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "TableWare",
    size: "Medium",
    category: "kansaUtensils",
  },

  {
    img: "https://tse1.mm.bing.net/th?id=OIP.XCH7nUNoI6uwV1YQeNaHIgHaGh&pid=Api&P=0&h=180",
    title: "Brass Glass",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "TableWare",
    color: "green",
    category: "Brass Utensils",
  },
  {
    img: "https://n4.sdlcdn.com/imgs/a/t/k/Kcl-Stainless-Steel-Plain-Thali-SDL068586344-1-7cad7.jpg",
    title: "Thali",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "TableWare",
    color: "black",
    category: "Steel Utensils",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.LtfYZXb-1Nd2aJS49FydygHaE8&pid=Api&P=0&h=180",
    title: "Dinner Set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "TableWare",
    color: "steel",
    category: "Steel Utensils",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.dbtWkabd1ZU2T5M7bCjX5wHaEI&pid=Api&P=0&h=180",
    title: "Kadai",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "600",
    company: "CookWare",
    color: "brozen",
    category: "Brass Utensils",
  },

  {
    img: "https://tse3.mm.bing.net/th?id=OIP.uz2riSXqRBVp7QxeYmynigHaFa&pid=Api&P=0&h=180",
    title: "Strainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "250",
    company: "CookWare",
    size: "Large",
    category: "Steel Utensils",
  },

  {
    img: "https://tse4.mm.bing.net/th?id=OIP.V7MRUX-caUOIt4Q04P9NawHaGt&pid=Api&P=0&h=180",
    title: "Tiffin",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Tiffins",
    size: "Large",
    category: "Steel Utensils",
  },

  {
    img: "https://tse3.mm.bing.net/th?id=OIP.01qerGjJdbjXvzdRuf4IsAHaE8&pid=Api&P=0&h=180",
    title: "CookingPan",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "CookWare",
    color: "blue",
    category: "Cooper Utensils",
  },

  {
    img: "https://angelichomeliving.com/wp-content/uploads/2021/10/gotham-steel-hammered-copper-cookware.jpg",
    title: " copper Dinner set",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "TableWare",
    color: "cooper",
    category: "Cooper Utensils",
  },
  {
    img: "https://n3.sdlcdn.com/imgs/a/m/2/Prisha-India-Craft-Pure-Copper-SDL897955075-1-49799.jpg",
    title: "Pure Copper Jug",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "TableWare",
    color: "red",
    category: "Copper Utensils",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.n6vva7wlRPost2HzgiOiMAHaGr&pid=Api&P=0&h=180",
    title: "Copper Bowl",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Tableware",
    color: "black",
    category: "Copper Utensils",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.o94c4BQ0N-g_EQUJfT18aAHaE8&pid=Api&P=0&h=180",
    title: "Milk Can",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "KitchenWare",
    color: "white",
    category: "Steel Utensils",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.GMDFW77cmnt5pXvI_blRJAHaHa&pid=Api&P=0&h=180",
    title: "Kansa ThaliSet",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Tableware",
    color: "black",
    category: "Kansa Utensils",
  },

  {
    img: "https://tse4.mm.bing.net/th?id=OIP.3CMQtdFkpeve9sFXTXkf3gHaEK&pid=Api&P=0&h=180",
    title: "ChefBOX",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "KitchenWare",
    color: "green",
    category: "Steel Utensils",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.kbrUwJjtz47zaxbVJnPQ3gHaGY&pid=Api&P=0&h=180",
    title: "Ghee Pot",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Kitchen Ware",
    color: "red",
    category: "KansaWare",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.0okkwc4BYSEFzyzbngrzEAHaG1&pid=Api&P=0&h=180",
    title: "Ptila",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "CookWare",
    color: "white",
    category: "Brass Utensils",
  },
  {
    img: "https://tse1.mm.bing.net/th?id=OIP.V9Zj2yrZGz5hS7Zgtv6V0QAAAA&pid=Api&P=0&h=180",
    title: "Pan",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "CookWare",
    color: "steel",
    category: "Steel Utensils",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.B_NEn1lc4E_rh0BnZWeg9QHaD-&pid=Api&P=0&h=180",
    title: "Masala Box",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "KitchenWare",
    color: "black",
    category: "Steel Utensils",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.0-jt5IXkFHvnmBgLvTdFyQHaHa&pid=Api&P=0&h=180",
    title: "Oil Container",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "KitchenWare",
    color: "black",
    category: "Steel Utensils",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.yKIOallTKxYp5KbvsMPrmAHaHa&pid=Api&P=0&h=180",
    title: "Water Bottle",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "KitchenWare",
    color: "black",
    category: "Steel Utensils",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.105B0NYGgm_U9X0WXWozXAHaG2&pid=Api&P=0&h=180",
    title: "Tiffin Box",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Tiffins",
    color: "red",
    category: "Kansa Utensils",
  },
  {
    img: "https://tse4.mm.bing.net/th?id=OIP.LQpyWodybni-7jFV-5GeoAHaF6&pid=Api&P=0&h=180",
    title: "Spoon",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "KitchenWare",
    color: "red",
    category: "Brass Utensils",
  },

  {
    img: "https://tse2.mm.bing.net/th?id=OIP.WDNpZzOpwv1T2h97y9bBHQHaIJ&pid=Api&P=0&h=180",
    title: "Serving Spoons",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "KitchenWare",
    color: "black",
    category: "Steel Utensils",
  },
  {
    img: "https://tse1.mm.bing.net/th?id=OIP.cKg_IUkhnyBx94pdL8wKRAHaHa&pid=Api&P=0&h=180",
    title: "Deep Dbba",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "KitchenWare",
    color: "black",
    category: "Steel Utensils",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.-9Du42KqYv4BWYA3m17VigHaHa&pid=Api&P=0&h=180",
    title: "Water Jug",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "KitchenWare",
    color: "white",
    category: "Steel Utensils",
  },
  {
    img: "https://tse2.mm.bing.net/th?id=OIP.gV8wjVhZr4ploKBDkffFawHaHa&pid=Api&P=0&h=180",
    title: "Atta Drum",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "KitchenWare",
    color: "black",
    category: "Brass Utensils",
  },
  {
    img: "https://tse3.mm.bing.net/th?id=OIP.B6RtDLk3Kgznlpi1fVqqugHaHa&pid=Api&P=0&h=180",
    title: "Copper Water Dispenser",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "KitchenWare",
    size :"Large",
    category: "Copper Utensils",
  },
];

export default data;
